### ISSUE TITLE
ssh into created instance

### ISSUE THREAD

**Issue by csgillespie** [cloudyr/aws.ec2#14]
Is it possible to ssh into the instance created in the README file?

```
i <- run_instances(image = image, 
                   type = "t2.micro", # <- you might want to change this
                   subnet = s[[1]], 
                   sgroup = g[[1]])
```

**Comment by leeper** [comment]
No, I suppose not. You need to specify a `keypair` argument with reference to a named keypair. See `? create_keypair`.

**Comment by leeper** [comment]
As of https://github.com/cloudyr/aws.ec2/commit/d517597f6a478a36ef337f09a4ff209fb25d4586, the README now contains a detailed example of this, which also uses the **ssh** package.
