### ISSUE TITLE
No public ip address return

### ISSUE THREAD

**Issue by csgillespie** [cloudyr/aws.ec2#15]
In the README, you have

```
# Launch the instance using appropriate settings
i <- run_instances(image = image, 
                   type = "t2.micro", # <- you might want to change this
                   subnet = s[[1]], 
                   sgroup = g[[1]])

# RStudio Server will be available at the "publicIp" address returned in `i`
# Note: the default security settings prohibit outbound traffic
```

However, `i` does not contain an element `publicIp`. I can manually log onto aws and view the public ip address .

**Comment by leeper** [comment]
Depends on the security group you've setup. By default, there may not be a public IP attached to an instance. Use `associate_ip()` to associate an IP with the security group or with the instance itself.
