### ISSUE TITLE
Proposal: Rename functions

### ISSUE THREAD

**Issue by csgillespie** [cloudyr/aws.ec2#19]
The function names are slightly misleading, since the input is **an** instance:
```
start_instances(instance, info, ...)
stop_instances(instance, force, ...)
terminate_instances(instance, ...)
reboot_instances(instance, ...)
```

Perhaps rename to 

```
start_instance
stop_instance
#etc
```

**Comment by leeper** [comment]
This can actually be an instance or a list of instances. I'm updating the documentation.
