### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by Emaasit** [cloudyr/aws.ec2#2]
Let me know which items are not ready yet so that I can contribute and accelerate development of this package. Thanks.

**Comment by leeper** [comment]
@Emaasit, thanks for your volunteering to help! As you can see by looking at the code, this is basically the outline of a package. It has no documentation and none of the functionality has been tested. I am willing to accept Pull Requests related to any part of the package. Documentation and writing testthat unit testing would be my top priorities, if you're looking for a way to contribute.

**Comment by arunkv** [comment]
I'm interested in contributing too but under which license are the cloudyr packages are being released?

**Comment by leeper** [comment]
All packages are currently licensed GPL.
