### ISSUE TITLE
Using filters with describe instances. 

### ISSUE THREAD

**Issue by itissid** [cloudyr/aws.ec2#24]
Hi I am not sure if I am using the filter correctly but its not working for me.
`describe_instances(filter=list("instance-state-name"="running"))`
I first tried the above, but that gives me the error:
```
No encoding supplied: defaulting to UTF-8.
Error in ec2HTTP(query = query, ...) :
  UnknownParameter: The parameter Key is not recognized
```
Even goin by the [Filter spec](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Filter.html) 
and tried the following:
```
describe_instances(filter=c("instance-state-name"=c("running"))
```
What am I doing wrong?

**Comment by leeper** [comment]
This should be fixed.
