### ISSUE TITLE
*describe_sgroups(filter)* does not work

### ISSUE THREAD

**Issue by nturaga** [cloudyr/aws.ec2#29]
In the code for `describe_sgroup(filter=list(description ='BLAH')` the filter function doesn't work. 

Because in the line , the function `.makelist` sets the names as ".Key"   , when it should be `.Name`

https://github.com/cloudyr/aws.ec2/blob/5ec77d363276db5f21978f63133205b1a8f2b9a8/R/misc.R#L3
```
 names(tmp) <- c(paste0(type, ".", 1:length(list), ".Key"),
```
This should be written as ` names(tmp) <- c(paste0(type, ".", 1:length(list), ".Name"),`

This doesn't work according to the aws api, as used here in describe_sgroups.

https://github.com/cloudyr/aws.ec2/blob/5ec77d363276db5f21978f63133205b1a8f2b9a8/R/SecurityGroups.R#L58
```
query <- c(query, .makelist(filter, type = "Filter"))
```

**Comment by leeper** [comment]
Fixed by https://github.com/cloudyr/aws.ec2/commit/90667f73de23fb7a831c42a25d3654bc1a4e4ed2
