### ISSUE TITLE
upstream xml2 1.2.0 changes break ec2HTTP()

### ISSUE THREAD

**Issue by peterfoley** [cloudyr/aws.ec2#36]
xml2 v1.2.0 changed the behavior of `as_list(read_xml(tmp))` to add an additional layer of nesting to the list output. See https://github.com/r-lib/xml2/releases/tag/v1.2.0

Many functions pull items from `ec2HTTP()` using `$` (ec. `r$imagesSet` in `describe_images()`) and all of those now return empty lists.

This may be the cause of #33, since error parsing in `ec2HTTP()` also uses output from `as_list(read_xml(tmp))` and expects it to have an `$Errors` element.

**Comment by leeper** [comment]
Thanks. Getting this updated and on CRAN is on my to-do list this month, so I'm good that.

**Comment by ignacio82** [comment]
is there a workaround this bug?

**Comment by leeper** [comment]
I think all of this was fixed by https://github.com/cloudyr/aws.ec2/commit/90667f73de23fb7a831c42a25d3654bc1a4e4ed2 (big thanks to @andrie!!). Let me know if not.
